data work.ordertype;
   set orion.orders;
   length Type $ 13 SaleAds $ 5;
   DayOfWeek=weekday(Order_Date);
   if Order_Type=1 then do;
      Type='Catalog Sale';
      SaleAds='Mail';
   end;
   else if Order_Type=2 then do;
      Type='Internet Sale';
	  SaleAds='Email';
   end;
   else if Order_Type=3 then do;
      Type='Retail Sale';
   end;
   drop Order_Type Employee_ID Customer_ID;
run;

proc print data=work.ordertype;
run;
