---
title: ""
output: pdf_document
---

**Joseph Blubaugh**  
 jblubau1@tamu.edu  
 **STAT 630-720**  
 **HW 04**
 
#### 1) 2.7.3
  a) Compute $P_x$: P(x) = 1/5 for Px(3, -2, 2, 3, 17), Px(x) = 0 otherwise
  b) Compute $P_Y$: P(y) = 1/5 for Py(-3, -2, 2, 3, 19), Py(y) = 0 otherwise
  c) Compute $P(Y > X)$: 3/5
  d) Compute $P(Y = X)$: 0
  e) Compute $P(XY < 0)$: 0
 
#### 2) 2.7.4: (change the range to $0 \le x \le 2, 0 \le y \le 1$ in part (d))
  a) $f_{X,Y}(x,y) = 2x^2 y + C y^5, for 0 \le x \le 1c, 0 \le y \le 1$, otherwise 0 
  
  \begin{align*}
  f_X(x) = x^2 + \frac{2}{3} \\
  \\
  f_Y(y) = \frac{2y}{3} \\
  \\
  C = 4 \\
  \\
  \int^0_{.6} \int^0_{.8} 2x^2y + 4y^5 \, dx dy  &= \\
  &= \int^0_{.6} \frac{x^3 y}{1.5} + 4y^5 |_0^{.8} \, dy \\
  &= \frac{.512 y^2}{3} + \frac{4y^6}{6} |_0^{.6} \\
  &= .088
  \end{align*}
  
  d) $f_{X,Y}(x,y) = C x^5 y^5, for 0 \le x \le 2, 0 \le y \le 1$
  
    \begin{align*}
  \int^1_0 \int^2_0 C x^5 y^5 \, dx dy &= \\
  \int^1_0 C x^5 y^5 \, dy &= C \frac{32}{3} \frac{y^6}{6} |_0^1 \\
  C &= \frac{9}{16} \\
  \\
  f_X(x) = \frac{9}{16} x^5 \\
  \\
  f_Y(y) = 6 y^5 \\
  \\
  \int^1_0 \int^2_0 \frac{9}{16} x^5 y^5 \, dx dy &= \int^1_0 3y^6 \, dy \\
  &= 3/7
  \end{align*}
  
#### 3) 2.7.9
  a) $f_X(x) = \frac{4 + 3x^2 - 2x^3}{8}$
  b) $f_Y(x) = \frac{6y + 8}{12}$
  c) $P(Y < 1) = \frac{1}{3}$
 
#### 4) 2.7.10 (apply the result in problem 2.7.13 without proof)
  a) $f_x(x) = \frac{1}{2 \sqrt{2 Pi}} e^{\frac{-(x - 3)^2}{8}}$  
  b) $f_y(y) = \frac{1}{4 \sqrt{2 pi}} e^{\frac{-(y -5)^2}{32}}$  
  c) not dependent because p != 0
 
#### 5) 2.7.16
  a) 
  \begin{align*}
  C \int^y_0 -e^{-(x + y) |_0^y} \, dy = 1 - e^{-2y} &= 1 \\
  &= \lim_{t \to \infty} y + \frac{e^{-2y}}{2} |_x^t \\
  C &= 1 \\
  \end{align*}
  b) $f_X(x) = \lim_{t \to \infty} -e^{-2t} + e^{-2x}$  
  $f_Y(y) = 1 - e^{-2y}$
 
#### 6) 2.8.1
  a) px(-2) = 3/12, px(9) = 3/12, px(13) = 6/12 
  b) py(3) = 8/12, py(5) = 4/12
  c) X and Y are all independent because in all cases Px(x)Py(y) = Pxy(x,y)
 
#### 7) 2.8.2
  a) Px(-2) = 5/16, Px(9) = 9/16, Px(13) = 2/16 
  b) Py(3) = 10/16, Py(5) = 6/16
  c) No, Px(x)Py(y) != Pxy(x,y)
 
#### 8) 2.8.5
  a) P(y=4 | x = 9) = 2/27
  b) P(y=-2 | x = 9) = 2/9
  c) P(y = 0 | x = -4) = 0
 
#### 9) 2.8.7: (change range to $0 \le x \le 2, 0 \le y \le 1$ in part d)  
  a) $F_{Y | X}(y | x) = \frac{2x^2y + 4y^5}{x^2 + 2/3}$, not independent
  d) $F_{Y | X}(y | x) = 6y^5$, not independent
 
#### 10) 2.8.10

  $P(x=1, y=1) = P(x=1) P(y=1) = \frac{P(x=1)P(y=1)}{P(Y=1)} = \frac{P(y=1)P(x=1)}{P(x=1)} = 1$
 
#### 11) 2.8.15
  a) $f_{X|Y}(x|y) = \frac{3x^2 + 3y}{y^3 + y}$
  b) $f_{Y|X}(y|x) = \frac{x^2 + y}{-4x^3 + 6x^2 + 8}$  
  c) x and y are not indepenent because $f_{x|y}(x|y) = \frac{f_{x,y}(x,y)}{f_y(y)} \ne f_x(x)$
 
#### 12) 2.8.23: (use result of 2.8.22 without proof)
  
  $\frac{{3 \choose 2} {2 \choose 1}  \theta 1 \theta 2}{{3 \choose 1}} = \frac{6 \theta 1 \theta 2}{3} = 2 \theta 1 \theta 2$
 
#### 13) 2.8.24
 
 $f_x1 = \int_0^{x1} \alpha e^{-\alpha y} \, dy$  
 $f_xn = \int_0^{xn} \alpha e^{-\alpha y} \, dy$  
 
#### 14) 2.9.7

z(2) = 0, z(4) = 1/2, z(5) = 1/12, z(7) = 1/12, z(8) = 1/24, z(9) = 0, z(11) = 3/4, z(12) = 3/8

#### 15) 2.9.14
 
 \begin{align*}
 f_Z(z) = P(x + y \le z) \\
 \\
 f_Z(z) = \int f_x(z - w) f_y(w) \, dw \\
 \\
 \frac{e^{\frac{-y^2}{2}}}{\sqrt{2 pi}} \int  \frac{\frac{e^{-(z-y)^2 / 2}}{\sqrt{2 pi}}}{2} \sqrt{2 pi} \\
 \end{align*}